version: "3.2"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db_dumps:/docker-entrypoint-initdb.d
      - db-mount:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: cross_copy
      MYSQL_DATABASE: backend_prod
      MYSQL_ENTRYPOINT_INITDB: ./mysql/docker-entrypoint-initdb.d
    networks:
      - internal
  redis:
    image: redis
    expose:
      - 6379
    networks:
      - internal
  backend:
    build: .
    command: bash -c "while ! (echo > /dev/tcp/db/3306) >/dev/null 2>&1; do sleep 1; done && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn cross_copy_backend.wsgi --reload -b 0.0.0.0:8000"
    container_name: backend
    restart: always
    volumes:
      - .:/app/backend
      - ./static:/app/backend/static:rw
    expose:
      - 8000
    networks:
      - internal
    environment:
      DJANGO_SETTINGS_MODULE: cross_copy_backend.settings.local
    depends_on:
      - db
      - redis

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 8000:8000
    volumes:
      - .:/app/backend
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:
volumes:
  db-mount:
